# Generated by Django 5.2 on 2025-05-18 20:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('location', '0002_voiture_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='Feature',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('gps', 'GPS'), ('ac', 'Air Conditioning'), ('bluetooth', 'Bluetooth'), ('usb', 'USB Port'), ('sunroof', 'Sunroof')], help_text='The name of the feature.', max_length=50, unique=True)),
            ],
        ),
        migrations.AddField(
            model_name='voiture',
            name='category',
            field=models.CharField(choices=[('sedan', 'Sedan'), ('suv', 'SUV'), ('hatchback', 'Hatchback'), ('coupe', 'Coupe'), ('van', 'Van')], default='sedan', help_text='The category of the car (e.g., SUV, Sedan).', max_length=20),
        ),
        migrations.AddField(
            model_name='voiture',
            name='transmission',
            field=models.CharField(choices=[('automatic', 'Automatic'), ('manual', 'Manual')], default='automatic', help_text='The transmission type of the car.', max_length=20),
        ),
        migrations.AddField(
            model_name='voiture',
            name='features',
            field=models.ManyToManyField(blank=True, help_text='The features available in the car.', to='location.feature'),
        ),
    ]
